name: surrealdb_query_builder
description: A Very Good Project created by Very Good CLI.
version: 0.2.0+2
repository: https://github.com/AyushChothe/surrealdb_query_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
