name: pub publish

on:
  push:
    tags:
      - "surrealdb_query_builder-v*.*.*"
  workflow_call:
    secrets:
      PUB_CREDENTIALS:
        required: true
        description: "Pub Credentials"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
    steps:
      - run: echo "Exposing env vars"

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    needs: vars
    with:
      dart_sdk: "stable"
      pub_credentials: ${{ needs.vars.outputs.PUB_CREDENTIALS }}
