name: pub publish

on:
  push:
    tags:
      - "surrealdb_query_builder-v*.*.*"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      dart_sdk: "stable"
      pub_credentials: secrets.PUB_CREDENTIALS
