name: pub publish

on:
  push:
    tags:
      - "surrealdb_query_builder-v*.*.*"
  workflow_call:
    secrets:
      PUB_CREDENTIALS:
        required: true
        description: "Pub Credentials"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      dart_sdk: "stable"
    secrets:
      pub_credentials: ${{ secrets.PUB_CREDENTIALS }}
